import sys

try:
    sys.stdout.reconfigure(encoding='utf-8')
except:
    pass

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# =====================================================
# EMAIL CONFIGURATION
# =====================================================

EMAIL_SENDER = "boatlabsrnd@gmail.com"
EMAIL_PASSWORD = "avhuyryqiklikgiq"

# EMAIL_RECEIVER = [
#     "jayakumar.v@imaginemarketingindia.com",
#     "naveen.m@imaginemarketingindia.com",
#     "rasiq.khan@imaginemarketingindia.com"
# ]

EMAIL_RECEIVER = [
    "jayakumar.v@imaginemarketingindia.com"
]

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587


# =====================================================
# COMMON EMAIL FUNCTION
# =====================================================

def send_email(subject, message):

    msg = MIMEMultipart()

    msg["From"] = EMAIL_SENDER
    msg["To"] = ", ".join(EMAIL_RECEIVER)
    msg["Subject"] = subject

    msg.attach(
        MIMEText(
            message,
            "plain",
            "utf-8"
        )
    )

    server = smtplib.SMTP(
        SMTP_SERVER,
        SMTP_PORT
    )

    server.starttls()

    server.login(
        EMAIL_SENDER,
        EMAIL_PASSWORD
    )

    server.sendmail(
        EMAIL_SENDER,
        EMAIL_RECEIVER,
        msg.as_string()
    )

    server.quit()

    print("Email sent successfully.")


# =====================================================
# IMMEDIATE ALERT EMAIL
# =====================================================

def send_alert_email(
        download,
        upload,
        ping,
        alerts,
        wifi_name,
        min_download,
        min_upload,
        max_ping):

    now = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    subject = (
        "🚨 [ALERT] "
        "Internet Issue Detected "
        "at boAt R&D Office"
    )

    message = f"""
Hi Team,

Internet issue detected at Bangalore boAt R&D office.

==================================================

Time          : {now}
WiFi          : {wifi_name}

==================================================
CURRENT NETWORK STATUS
==================================================

Download      : {download} Mbps
Upload        : {upload} Mbps
Ping          : {ping} ms

==================================================
CONFIGURED THRESHOLDS
==================================================

Min Download  : {min_download} Mbps
Min Upload    : {min_upload} Mbps
Max Ping      : {max_ping} ms

==================================================
TRIGGERED ALERTS
==================================================
"""

    for alert in alerts:
        message += f"- {alert}\n"

    message += """
==================================================

Please check the network.

Regards,
boAt R&D
Internet Monitor Bot
"""

    send_email(subject, message)


# =====================================================
# HOURLY SUMMARY EMAIL
# =====================================================

def send_summary_email(log_content):

    subject = (
        "🚨 boAt R&D Bangalore "
        "- Hourly Internet Health Report 🛜"
    )

    report_time = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    message = f"""
Hi Team,

Please find the Internet Monitoring Summary Report.

Generated Time:
{report_time}

==================================================
INCIDENT SUMMARY
==================================================

{log_content}

==================================================
This is an automated report generated by the
boAt R&D Internet Monitoring System.

Regards,
boAt R&D [Internet Health Monitor Bot]
"""

    send_email(subject, message)


# =====================================================
# LOCAL TEST
# =====================================================

if __name__ == "__main__":

    send_summary_email(
        "Test Summary Email"
    )
    
    