import sys

try:
    sys.stdout.reconfigure(encoding='utf-8')
except:
    pass

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# =====================================================
# EMAIL CONFIGURATION
# =====================================================

EMAIL_SENDER = "boatlabsrnd@gmail.com"
EMAIL_PASSWORD = "avhuyryqiklikgiq"

# EMAIL_RECEIVER = [
#     "jayakumar.v@imaginemarketingindia.com",
#     "naveen.m@imaginemarketingindia.com",
#     "rasiq.khan@imaginemarketingindia.com"
# ]

EMAIL_RECEIVER = [
    "jayakumar.v@imaginemarketingindia.com"
]

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587


# =====================================================
# COMMON EMAIL FUNCTION
# =====================================================

def send_email(subject, message):

    msg = MIMEMultipart()

    msg["From"] = EMAIL_SENDER
    msg["To"] = ", ".join(EMAIL_RECEIVER)
    msg["Subject"] = subject

    msg.attach(
        MIMEText(
            message,
            "plain",
            "utf-8"
        )
    )

    server = smtplib.SMTP(
        SMTP_SERVER,
        SMTP_PORT
    )

    server.starttls()

    server.login(
        EMAIL_SENDER,
        EMAIL_PASSWORD
    )

    server.sendmail(
        EMAIL_SENDER,
        EMAIL_RECEIVER,
        msg.as_string()
    )

    server.quit()

    print("Email sent successfully.")

# =====================================================
# HOURLY SUMMARY EMAIL
# =====================================================

def send_summary_email(log_content):

    subject = (
        "🚨 Internet Health Summary Report "
        "- boAt R&D Bangalore Office 🛜"
    )

    report_time = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    message = f"""
Hi Team,
Please find the Internet Monitoring Summary Report.
{log_content}
===============
This is an automated report generated by the
boAt R&D Internet Monitoring System.

Regards,
boAt R&D [Internet Health Monitor Bot]
"""

    send_email(subject, message)


# =====================================================
# LOCAL TEST
# =====================================================

if __name__ == "__main__":

    send_summary_email(
        "Test Summary Email"
    )
    
    